---
apiVersion: v1
kind: Service
metadata:
  name: clouddatalayer
  namespace: default
  labels:
    app: clouddatalayer
spec:
  ports:
  - name: http
    #nodePort: 31880
    port: 8080
    protocol: TCP
    targetPort: 8084
  type: LoadBalancer
  selector:
 #  run: clouddatalayer
   app: clouddatalayer
   version: v1
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clouddatalayer
  namespace: default
  labels:
    app: clouddatalayer
    version: v1
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clouddatalayer
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clouddatalayer
        version: v1
    spec:
      containers:
      - name: clouddatalayer
        image: kapilshekharraina/clouddatalayer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
         requests:
          cpu: "100m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: restcachevol # 
        emptyDir: {}
