spring:
  application:
    name: clouddatalayer
 
server:
  port: 8084
  
     
logging:
  pattern:
    level: "[%X{X-B3-TraceId} : %X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"
  level:
    root: INFO
    com.scg.service: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO